### ISSUE TITLE
EIP-721 assets can start with tokenID:0 but CAIP-19 starts from tokenId:1

### ISSUE THREAD

**Issue by TimDaub** [ChainAgnostic/CAIPs#117]
- see here: https://github.com/ChainAgnostic/CAIPs/blob/6beec4de64faafaaf8beabddec959afbe9275d9c/CAIPs/caip-19.md?plain=1#L50
- here's a random NFT and you can call `tokenURI(0)`: https://etherscan.io/address/0x9CB7712C6A91506e69E8751fcb08e72e1256477D#readContract

from EIP-721: https://eips.ethereum.org/EIPS/eip-721

> NFT Identifiers

> Every NFT is identified by a unique uint256 ID inside the ERC-721 smart contract. This identifying number SHALL NOT change for the life of the contract. The pair (contract address, uint256 tokenId) will then be a globally unique and fully-qualified identifier for a specific asset on an Ethereum chain. While some ERC-721 smart contracts may find it convenient to start with ID 0 and simply increment by one for each new NFT, callers SHALL NOT assume that ID numbers have any specific pattern to them, and MUST treat the ID as a “black box”. Also note that NFTs MAY become invalid (be destroyed). Please see the enumeration functions for a supported enumeration interface.

**Comment by ntn-x2** [comment]
I think you are confusing the minimum length of the token ID with its value. The regex `[-a-zA-Z0-9]{1,78}` means that you can use any character in the set `-`, `[a-z]`, `[A-Z]`, `[0-9]` for at least 1 and at most 78 times. So the charset already allows for an ID of `0`.

**Comment by TimDaub** [comment]
makes sense, my bad
