### ISSUE TITLE
ETH2 CAIP-2

### ISSUE THREAD

**Issue by orenyomtov** [ChainAgnostic/CAIPs#127]
Following the upcoming scheduled merge, having clear CAIP-2 blockchain identifiers can be greatly beneficial for navigating the ambiguities for both the humans and the machines involved in this space.

What will be the CAIP-2 identifier for:
1. ETH1
2. ETH2
3. ETC

Best,
Oren

**Comment by bumblefudge** [comment]
I feel like this topic should be discussed in detail and notes captured at the next meeting... putting it in the draft agenda now before we forget.

**Comment by bumblefudge** [comment]
Reminder: at last meeting we discussed how the merge created a new complexity to the ongoing block-number query conversation: post-consensus, pre-execution transactions will not have a block# yet, and will also not be in `block=latest`, but rather, for an unknowable number of blocks, it will be in "safe" executive limbo! So the forthcoming CAIP about block-number query will have to grapple with this.
