### ISSUE TITLE
CAIP-25: Is "handshake" the appropriate word for the CAIP-25 procedure?

### ISSUE THREAD

**Issue by rekmarks** [ChainAgnostic/CAIPs#142]
Ref: #138 

## Problem

Participants raised the point that "handshake" may be an inappropriate term for the CAIP-25 procedure and the associated method. Specifically, "handshaking" is used in telecommunications between two parties to determine that they are using the same communications protocol. In our case, by the time a `caip_handshake` request is made, this has of course already been established.

**Comment by kdenhartog** [comment]
I was thinking this would be more like a `wallet_authorize` call. It seems like the primary purpose of this is to act as an encapsulation API that handles requests for additional API calls so it's less about a handshake as the access is already accessible (as you pointed out) and more focused on requesting additional permissions from the wallet.
