### ISSUE TITLE
CAIP-2: chain ID alias

### ISSUE THREAD

**Issue by jdsika** [ChainAgnostic/CAIPs#267]
Is it allowed to introduce a "chain ID alias" in a caip-2 namespace derivative as a lot blockchains (like e.g. Tezos) use a non-so-human-readable chain ID but the social consensus is to use the name 'mainnet' for a certain chain as chain id.

I came up with this question while creating this PR (https://github.com/ChainAgnostic/namespaces/pull/104)

**Comment by oed** [comment]
Generally we've been wanting CASA to not have to maintain registries of _names -> numbers_. That's why genesis block hashes has been picked. If you know of existing registries that we can point to that would make things easier.

**Comment by jdsika** [comment]
ok, I would keep the alias in the CAIP-2 tezos namespace for now and have created a ticket: https://gitlab.com/tezos/tezos/-/issues/7023

I described a link of the alias and chain ID through an option in the Octez reference implementation. Thx for the information - I will close the issue.
