### ISSUE TITLE
CAIP-2 (Chain ID): The Ethereum interface

### ISSUE THREAD

**Issue by webmaster128** [ChainAgnostic/CAIPs#3]
This is ticket is about the details of the Ethereum interface for #2.

-------

## Interface name

The name of this interface should either be "ethereum", referring to the wider Ethereum ecosystem.

## Reference definition

The definition is delegated to [EIP155](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-155.md). The reference format is `eip155-%d`, where `%d` is an unsigned integer in decimal represenation and corresponds to `CHAIN_ID` of EIP155.

Note: due to length restrictions of the `reference` field, the largest supported `CHAIN_ID` is 9999999999999999999999999999999999999999.

## Examples

```
# Ethereum mainnet
ethereum:eip155-1

# Görli
ethereum:eip155-5

# Auxilium Network Mainnet
ethereum:eip155-28945486
```

Open questions:

- [x] ~Do we want interface name `ethereum` or `evm`?~ `ethereum`, see https://github.com/ChainAgnostic/CAIPs/issues/3#issuecomment-559554777
- [x] ~Should we drop the "eip155-" prefix?~ No, see https://github.com/ChainAgnostic/CAIPs/issues/3#issuecomment-559864996

**Comment by ligi** [comment]
My gut feeling is that we should use ethereum here. The only advantage I see for evm is that it is shorter. But then we should better take eth as it is about ethereum and not the virtual machine IMHO. But waiting for @pedrouid to ship in before stating my final signaling - just saying where I lean to curently

**Comment by pedrouid** [comment]
Personally I'm not that strong on the `evm` prefix so I would be happy to go with the `ethereum` one

**Comment by webmaster128** [comment]
@pedrouid any 👍 or 👎 for dropping the "eip155-" prefix within the "ethereum" interface?

**Comment by pedrouid** [comment]
This is actually important because some private Ethereum/EVM chains may have chainIds not compatible with EIP-155, something that was pointed out by the uPort team. Additionally this makes it easier to distinguish from networkId's which are still commonly used by Dapps.

**Comment by webmaster128** [comment]
@pedrouid great, thanks. Do you know a different type of network ID that belongs into the Ethereum interface and could be covered here as well?

**Comment by pedrouid** [comment]
I would just assume that a private Ethereum chain using a chainId that is not compatible with EIP-155 is following the CAIP-2 but not the CAIP-3. Hence it has `ethereum` interface but has an arbitrary `reference` string

**Comment by webmaster128** [comment]
Done in #9

**Comment by ligi** [comment]
the prefix eip155 is used as we use chainIDs introduced in eip155 to specify the chains. Also ethereum: is already used by ERC681
