### ISSUE TITLE
CAIP-2 (Chain ID): The Bitcoin interface

### ISSUE THREAD

**Issue by webmaster128** [ChainAgnostic/CAIPs#4]
This is ticket is about the details of the Bitcoin interface for #2.

-------

## Interface name

The name of this interface should be "bitcoin", referring to the wider Bitcoin ecosystem, including multiple forks of the chain and the code.

## Reference definition

The definition is delegated to [BIP122](https://github.com/bitcoin/bips/blob/master/bip-0122.mediawiki#definition-of-chain-id). The reference format is `bip122-%s`, where `%s` is a 32 character prefix of the block hash from BIP122 (lower case hex).

## Blockchains in this interface

* Bitcoin + chain forks
* Litecoin + chain forks (e.g. Feathercoin)

## Blockchains not in this interface

* ZCash: BIP122 excluded explicitely by https://github.com/zcash/zips/issues/87#issuecomment-250988155. Further research may be necessary to understand why and if there is an alternative blockchain ID specification.

## Examples

```
# Bitcoin mainnet (see https://github.com/bitcoin/bips/blob/master/bip-0122.mediawiki#definition-of-chain-id)
bitcoin:bip122-000000000019d6689c085ae165831e93

# Litecoin
bitcoin:bip122-12a765e31ffd4059bada1e25190f6e98

# Feathercoin (Litecoin fork)
bitcoin:bip122-fdbe99b90c90bae7505796461471d89a
```

Open questions:

- [ ] Should we drop the "bip122-" prefix?
- [ ] How to find a list of important blockchains that can be covered by this interface? What about e.g. Bitcoin Cash, Monero, ~Zcash~, …

**Comment by webmaster128** [comment]
Done in #9

**Comment by daira** [comment]
> ZCash: BIP122 excluded explicitely by https://github.com/zcash/zips/issues/87#issuecomment-250988155. Further research may be necessary to understand why and if there is an alternative blockchain ID specification.

Just to clarify, Zcash excluded that BIP from its specification only because it was in Draft at the time (2016-10-02). It became Active on 2016-11-30 according to its [history on GitHub](https://github.com/bitcoin/bips/commits/master/bip-0122.mediawiki). All Draft BIPs as of 2016-10-02 were excluded, and this one wasn't going to affect consensus anyway.

**Comment by Mohmmedghalibe** [comment]
000000000019d6689c085ae165831e93
