### ISSUE TITLE
Token ID for Ethereum 721/1155 NFTs: Change to hex-string

### ISSUE THREAD

**Issue by ukstv** [ChainAgnostic/CAIPs#58]
The current specification for Ethereum NFTs (both [CAIP-22](https://github.com/ChainAgnostic/CAIPs/blob/master/CAIPs/caip-22.md) and [CAIP-29](https://github.com/ChainAgnostic/CAIPs/blob/master/CAIPs/CAIP-29.md)) silently assumes that token id can be represented as integer, like `eip155:1/erc1155:0x28959Cf125ccB051E70711D0924a62FB28EAF186/0` or `eip155:1/erc721:0x06012c8cf97BEaD5deAe237070F9587f8E7A266d/771769`. It is worth noting that token id in the respective ERCs are `uint256` which exceeds usual number representation of almost every programming language.

In order to parse _large_ token id, one has to rely on some sort of big integer support, be it a library or language-provided feature. For JS, which is the predominant language and platform to interoperate with blockchains, this requires either ES2020 (which is a big pain for library authors, because of deficient bundlers used downstream) for native `BigInt` or using some heavy library like `BigNumber.js`. At the same time, if the token id is passed as hex-string, i.e. `0xbc6b9` for `771769`, there is no need for the dangerous tricks. Moreover, it seems, like hex representation for token id is already commonly used in applications.

So, here is a request for comments. Let's adjust the specifications for EIP1155 and EIP721, so that token id is represented as a hex-string.

CC @mikehroth, @oed

**Comment by oed** [comment]
I'm kind of leaning towards it being worth biting the bullet with `BigInt` on this one. It will just be so much easier for users and devs to reason about the NFT CAIPs if they don't have to do any programmatic conversions of numbers!

**Comment by mikehroth** [comment]
I'd have to agree with @oed. Most blockchain SDKs / libraries use some form of BigNumber library for better dev UX. 
For example [ethers uses BN.js](https://docs.ethers.io/v5/api/utils/bignumber/) - which they chose primarily because a lib they are dependent on (elliptic) also uses BN.js. It might be a good idea to do what they did and see if any dependencies are already loading a BigNumber lib and use the same one to reduce dependency size.

**Comment by ukstv** [comment]
Cool. No hex then :) Closing.
