### ISSUE TITLE
go-caip

### ISSUE THREAD

**Issue by tarrencev** [ChainAgnostic/CAIPs#62]
I'm working on a go implementation of CAIP i'd love to contribute to the organization if you are interested: https://github.com/tarrencev/go-caip

**Comment by pedrouid** [comment]
This would be great 👌 I also would like to migrate my JS implementation to this org

cc @ligi

**Comment by ligi** [comment]
@tarrencev cool - just invited you to the org! happy to move this repo over if you want

**Comment by tarrencev** [comment]
awesome! i'll move it over sometime this week.

**Comment by tarrencev** [comment]
done!
